### ISSUE TITLE
Error message after .png generation

### ISSUE THREAD

**Issue by fpvandi** [kirek007/ws-osd-py#53] opened 2023-03-27 14:54 UTC
Hello together,

when i try to render my videos from the internal hard drive i get an error message that there are no .png available. When I then go into the AvatarGxxxx_generated folder it is actually empty. As soon as the video files and the .srt and .osd files are on another drive (e.g. external SSD or microSd card) I can render the videos normally.
Is this error known or is it just me?

![image](https://user-images.githubusercontent.com/129083871/227978057-9c2b8fef-598b-4710-90da-53b47a2c3dc9.png)

**Comment by kirek007** [comment] 2023-03-27 14:57
Hey, I'm quite sure that this is relate to space in directory path. Sadly
this is bug in library I'm using and can't be fixed today :(
Please try to generate in different directory

pon., 27 mar 2023, 16:54 użytkownik fpvandi ***@***.***>
napisał:

**Comment by fpvandi** [comment] 2023-03-27 15:16
Thanks for the quick response.
I found the mistake in the directory path, I am from germany and we have special letter like ä oder ü.
And i had one ä in the path that was the mistake. Changes ä to ae and now it works.

**Comment by kirek007** [comment] 2023-03-27 20:00
Duplicate of #23

**Closed as completed by kirek007** 2023-03-27 20:00 UTC
